#!/bin/sh

# Convenience dispatcher for all Boxing utilites

export BOXING_INSTALL_DIR="$(dirname "$(readlink -f "$0")")"

help(){
cat <<HEREDOC
Usage: boxing [--help] [--list] [--version] <command>

boxing --help, Display this message and exit.
boxing --list, List available boxing commands and exit.
boxing --update, Update boxing tools and exit.
boxing --version, Display version and exit.
boxing <command>, Run command and exit.

Available commands:
$(list)
HEREDOC
}

list(){
    for i in "$BOXING_INSTALL_DIR"/*; do
        if [ -d "$i" ]; then
        local cmd="$(basename "$i")"
        if [ -x "$i"/"$cmd" ]; then
                printf "%s\n" "$cmd"
            fi
        fi
    done
}

update(){
    boxing setups --source-github hedinfaok/boxing/HEAD/boxing.setups.sh
}

version(){
    printf "%s.%s.%s-%s\n" 0 2 1 fry
}

_dispatch(){
    if [ -x "$BOXING_INSTALL_DIR"/"$1"/"$1" ]; then
        cmd="$1"
        shift
        exec "$BOXING_INSTALL_DIR"/"$cmd"/"$cmd" "$@"
    else
        help
    fi
}

boxing(){
    if [ $# -gt 0 ]; then
        case "$1" in
            --help|-h|help)
                help ;;
            --list|-l|list)
                list ;;
            --update|-u|update)
                update ;;
            --version|-v|version)
                version ;;
            *) _dispatch "$@" ;;
        esac
    else
        help
    fi
}

boxing "$@"
