name: CI
on:
  push:
    branches:
      - prototype

  pull_request:
    types:
      - opened
      - reopened
      - synchronize

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        DOCKER_IMAGE: ["bash:3.2", "bash:4", "bash:5"]

    container:
      image: ${{ matrix.DOCKER_IMAGE }}
      options: --cpus 1

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: apk add --update-cache curl shellcheck bats
      - run: bash --version
      - run: echo curl -s "https://raw.githubusercontent.com/hedinfaok/boxing/${GITHUB_REF}/boxing.setups.sh"
      - run: curl -s "https://raw.githubusercontent.com/hedinfaok/boxing/${GITHUB_REF}/boxing.setups.sh" | bash -x
      - run: $HOME/.local/bin/boxing --version
      - run: $HOME/.local/bin/boxing --list
      - run: $HOME/.local/bin/setups --version
